# Set this to the URL of your workflow
@workflowUrl = <workflow-url>

###

# Test a valid URL - Should return 200 OK
POST {{workflowUrl}}
Content-Type: application/json

{
  "testName": "My Test",
  "urlToTest": "https://github.com/ronaldbosma/LogicApps.ServiceProviders.ApplicationInsights.TrackAvailability"
}

###

# Test an invalid URL - Should return 503 Service Unavailable
POST {{workflowUrl}}
Content-Type: application/json

{
  "testName": "My Test",
  "urlToTest": "https://github.com/ronaldbosma/LogicApps.ServiceProviders.ApplicationInsights.TrackAvailability/404"
}