# Set this to the URL of your workflow
@workflowUrl = "..."

###

# Test a valid URL
POST {{workflowUrl}}
Content-Type: application/json

{
  "testName": "My Test",
  "urlToTest": "https://github.com/ronaldbosma/LogicApps.ServiceProviders.ApplicationInsights.TrackAvailability"
}

###

# Test an invalid URL
POST {{workflowUrl}}
Content-Type: application/json

{
  "testName": "My Test",
  "urlToTest": "https://github.com/ronaldbosma/LogicApps.ServiceProviders.ApplicationInsights.TrackAvailability/404"
}